### ISSUE TITLE
The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 9 (near "- @service_container")

### ISSUE THREAD

**Issue by sagaraspl** [joschi127/doctrine-entity-override-bundle#1]
Hi In symfony 3 It won't allow to write @service_container without single/double quote.

joschi127/doctrine-entity-override-bundle/Resources/config/services.yml

Need to replace @service_container with '@service_container'

**Comment by sagaraspl** [comment]
@joschi127 when will you do this fix?

**Comment by joschi127** [comment]
Thanks for reporting.

Fixed in https://github.com/joschi127/doctrine-entity-override-bundle/commit/f4e0c8faa37f09832e609a49f9ca5fede77162fb

**Comment by joschi127** [comment]
Also tagged a new release v0.3.1
