### ISSUE TITLE
After overwriting entity many to many relation not working while saving the data

### ISSUE THREAD

**Issue by sagaraspl** [joschi127/doctrine-entity-override-bundle#2]
Hi @joschi127 

If I have USER entity at vendor level and It has many to many with roles and after using your bundle and overwriting the USER entity at application level, when loading fixture using doctrine fixture the addRole method not saving data into many to many relation when trying to save using source entity. Though it is working when using overwritten entity but it Many to Many relation should also work with base or source entity. Suppose I am putting following...

joschi127_doctrine_entity_override:
    overridden_entities:
        Fa\Bundle\UserBundle\Entity\User: App\Bundle\UserBundle\Entity\User

Then it should work with Fa\Bundle\UserBundle\Entity\User as well.

**Comment by sagaraspl** [comment]
Seems not a valid case. I need to check more

**Comment by joschi127** [comment]
I think I have similar cases in projects where it is working. But maybe it is broken with newer versions of Symfony or Doctrine.

I will check it and try to add some tests to this bundle.

**Comment by sagaraspl** [comment]
@joschi127 Thanks in advance. This is really important that this will work with latest doctrine and symfony version.

**Comment by joschi127** [comment]
Ok, can reproduce it, added a failing test here https://github.com/joschi127/doctrine-entity-override-bundle/commit/f3188ce53ae457f72abfeb1b8855c854345a80f4

Will have a closer look at it and try to fix it.

**Comment by joschi127** [comment]
@sagaraspl Just released https://github.com/joschi127/doctrine-entity-override-bundle/releases/tag/v0.4.1 with a lot of improvements. Let me know if it works for you. Thanks :-)

**Comment by joschi127** [comment]
And 0.4.2 released with another fix. Thanks for testing and for your feedback.
