### ISSUE TITLE
Issue for updating using composer

### ISSUE THREAD

**Issue by sagaraspl** [joschi127/doctrine-entity-override-bundle#3]
Hi @joschi127 Thanks for quick response but it seems that I am not able to update the package using composer because of:

symfony/symfony: ~2.7,>=2.7.12|~3.1
symfony/framework-bundle: ~2.7,>=2.7.12|~3.1

because symfony 3.1 is in beta yet and I am using symfony 3.0, so above requirements should be like...

symfony/symfony: ~2.7,>=2.7.12|~3.0
symfony/framework-bundle: ~2.7,>=2.7.12|~3.0

what do you think?

**Comment by sagaraspl** [comment]
php composer.phar require joschi127/doctrine-entity-override-bundle
Using version ^0.4.1 for joschi127/doctrine-entity-override-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)  
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for joschi127/doctrine-entity-override-bundle ^0.4.1 -> satisfiable by joschi127/doctrine-entity-override-bundle[v0.4.1].
    - Conclusion: remove symfony/symfony v3.0.2
    - Conclusion: don't install symfony/symfony v3.0.2
    - joschi127/doctrine-entity-override-bundle v0.4.1 requires symfony/symfony ~2.7,>=2.7.12|~3.1 -> satisfiable by symfony/symfony[2.7.x-dev, 2.8.x-dev, 3.1.x-dev, 3.2.x-dev].
    - Can only install one of: symfony/symfony[2.7.x-dev, v3.0.2].
    - Can only install one of: symfony/symfony[2.8.x-dev, v3.0.2].
    - Can only install one of: symfony/symfony[3.1.x-dev, v3.0.2].
    - Can only install one of: symfony/symfony[3.2.x-dev, v3.0.2].
    - Installation request for symfony/symfony == 3.0.2.0 -> satisfiable by symfony/symfony[v3.0.2].

Installation failed, reverting ./composer.json to its original content.

**Comment by joschi127** [comment]
@sagaraspl 

Compatibility with Symfony 3.0.x should be fixed not as well with commit https://github.com/joschi127/doctrine-entity-override-bundle/commit/26449ab9a4af9fbcdc9d243d5e61a111927d8766

I also tagged a new release https://github.com/joschi127/doctrine-entity-override-bundle/releases/tag/v0.4.3

But you need at least Symfony 3.0.6. With Symfony 3.0.2 it did not work for me. I do not know why.

Please check and let me know. Thanks a lot!

**Comment by sagaraspl** [comment]
Hi @joschi127 

Now it is giving another issue with doctrine while updating using composer.

php composer.phar update joschi127/doctrine-entity-override-bundle
Loading composer repositories with package information
Updating dependencies (including require-dev)  
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for joschi127/doctrine-entity-override-bundle 0.4.3 -> satisfiable by joschi127/doctrine-entity-override-bundle[v0.4.3].
    - Can only install one of: doctrine/doctrine-bundle[1.6.x-dev, 1.6.1].
    - Can only install one of: doctrine/doctrine-bundle[1.6.x-dev, 1.6.1].
    - Can only install one of: doctrine/doctrine-bundle[1.6.x-dev, 1.6.1].
    - joschi127/doctrine-entity-override-bundle v0.4.3 requires doctrine/doctrine-bundle ~1.6,>=1.6.2 -> satisfiable by doctrine/doctrine-bundle[1.6.2, 1.6.x-dev].
    - Conclusion: don't install doctrine/doctrine-bundle 1.6.2
    - Installation request for doctrine/doctrine-bundle == 1.6.1.0 -> satisfiable by doctrine/doctrine-bundle[1.6.1].

doctrine/doctrine-bundle: ~1.6,>=1.6.2

**Comment by joschi127** [comment]
Looks like you are using doctrine-bundle 1.6.1 but the entity override bundle requires at least 1.6.2.

So if you update doctrine-bundle to 1.6.2 (e.g. by editing your composer.json and running composer update) it should work.
