### ISSUE TITLE
Great job, could You please release a tag?

### ISSUE THREAD

**Issue by simara-svatopluk** [joschi127/doctrine-entity-override-bundle#9]
Hi,
this bundle looks and seem to work great even with translations and tree bundle, good job!
May I ask You to release a new tag based on a current master?

**Comment by joschi127** [comment]
New Release is tagged.

Thanks very much for your positive feedback. However, all credit goes to @pjedrzejewski because the solution is actually based on his code, as used in https://github.com/Sylius/SyliusResourceBundle :-)
